name: markusvieghofer.at
description: Software made in Österreich
meta_description: 'Your New Jekyll Site, Blogging about stuffs'

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://markusvieghofer.at'
google_analytics: 'UA-83732990-1'
gems: [jekyll-paginate]

permalink: /:slug

# Details for the RSS feed generator
url:                'http://markusvieghofer.at'
author:             'Markus Vieghofer'
author_description: "I love developing software. Most of the time I stick with Java and Android but I also try something new from time to time. I'm  also on <a href='https://twitter.com/mvieghofer' target='_blank'>Twitter</a> and <a href='https://github.com/mvieghofer' target='_blank'>Github</a>."
